name: 'Build'

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build
      - name: Archive built file
        uses: actions/upload-artifact@v3
        with:
          name: local-conditional-card
          path: dist/local-conditional-card.js
